In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import Imputer, StandardScaler
from io import StringIO

In [2]:
import os
path = os.getcwd()
print(path)

/Users/jdear/HBSDissertation

In [3]:
os.chdir('/Users/jdear/HBSDissertation')
path = os.getcwd()
print(path)

/Users/jdear/HBSDissertation

In [4]:
testAccData = pd.read_csv('/Users/jdear/HBSDissertation/testaccountdata.csv')
testAccData.head(5)

,_,Id,Name,Account__c,Account__r,Account__r.CSG_Coverage__c,Account__r.AOV_Band__c,Account__r.CSM_lookup__c,Account__r.CSM_lookup__r,Core_SFA_EWS_360_Score__c,...,Core_Service_EWS_360_Score__c,Weighted_EWS_Score__c,Platform_Adoption__c,Lightning_Adoption__c,Current_Adoption_Growth__c,TLP_TTM30Days_SalesService__c,FY_TLP_Baseline_SalesService__c,TLP_30Days_SalesService__c,EWS_360_Scores_Snap_Date__c,Account__r.CSM_lookup__r.Name
0,[Account_Detail__c],aAR0M0000001vKBWAY,672027,0010M00001SeSYVQA3,[Account],Focus,$0,NaN,NaN,14.0,...,NaN,6120,0.00,No Lightning Usage,-36.48,33.333333,53.333333,33.33,2021-06-01,NaN
1,[Account_Detail__c],aAR0M0000001uzJWAQ,670733,0013000000NPF3iAAH,[Account],Focus,$1M-5M,0053y00000G7Q5CAAV,[User],91.0,...,81.0,8132,0.57,Lightning Enabled,-6.03,75.468867,91.558442,64.04,2021-05-01,Simona Serena
2,[Account_Detail__c],aAR0M0000001unaWAA,670006,0010M00001SmqRAQAZ,[Account],Focus,$0,NaN,NaN,56.0,...,NaN,864,0.79,Lightning Enabled,-5.02,40.000000,44.000000,57.14,2021-06-01,NaN
3,[Account_Detail__c],aAR0M0000001v6YWAQ,671182,0010M00001QmstNQAR,[Account],Top,$10k-50k,NaN,NaN,28.0,...,47.0,1406,0.09,Lightning Enabled,1.66,83.144919,86.908113,81.08,2021-06-01,NaN
4,[Account_Detail__c],aAR0M0000001uiqWAA,669712,0010M00001SmqRUQAZ,[Account],Focus,$0,NaN,NaN,63.0,...,NaN,576,0.79,No Lightning Usage,-4.88,33.333333,38.666667,33.33,2021-06-01,NaN

In [6]:
testAccData.describe()

,Name,Core_SFA_EWS_360_Score__c,Core_Service_EWS_360_Score__c,Weighted_EWS_Score__c,Platform_Adoption__c,Current_Adoption_Growth__c,TLP_TTM30Days_SalesService__c,FY_TLP_Baseline_SalesService__c,TLP_30Days_SalesService__c
count,100.000000,60.000000,44.000000,100.000000,99.000000,93.000000,93.000000,93.000000,100.000000
mean,625145.590000,46.000000,58.500000,21406.140000,0.444949,1395.531828,63.641166,69.137178,57.288200
std,170833.579071,23.868993,24.574992,72590.218329,0.312871,12070.093571,27.385870,28.353222,33.724788
min,107596.000000,7.000000,13.000000,0.000000,0.000000,-69.700000,0.000000,0.000000,0.000000
25%,650462.000000,26.750000,33.000000,412.500000,0.165000,-17.520000,40.899123,53.333333,32.497500
50%,670161.000000,48.500000,64.000000,1445.000000,0.390000,-4.880000,70.228739,75.000000,65.810000
75%,685552.000000,63.250000,81.000000,8575.250000,0.790000,8.820000,83.144919,91.833397,85.777500
max,754690.000000,91.000000,91.000000,592833.000000,0.980000,115698.650000,100.000000,100.000000,100.000000

In [8]:
del testAccData['_']
testAccData.head(5)

,Id,Name,Account__c,Account__r,Account__r.CSG_Coverage__c,Account__r.AOV_Band__c,Account__r.CSM_lookup__c,Account__r.CSM_lookup__r,Core_SFA_EWS_360_Score__c,Lightning_Adoption_Stage__c,Core_Service_EWS_360_Score__c,Weighted_EWS_Score__c,Platform_Adoption__c,Lightning_Adoption__c,Current_Adoption_Growth__c,TLP_TTM30Days_SalesService__c,FY_TLP_Baseline_SalesService__c,TLP_30Days_SalesService__c,EWS_360_Scores_Snap_Date__c,Account__r.CSM_lookup__r.Name
0,aAR0M0000001vKBWAY,672027,0010M00001SeSYVQA3,[Account],Focus,$0,NaN,NaN,14.0,0. None / Unknown,NaN,6120,0.00,No Lightning Usage,-36.48,33.333333,53.333333,33.33,2021-06-01,NaN
1,aAR0M0000001uzJWAQ,670733,0013000000NPF3iAAH,[Account],Focus,$1M-5M,0053y00000G7Q5CAAV,[User],91.0,4. Activation,81.0,8132,0.57,Lightning Enabled,-6.03,75.468867,91.558442,64.04,2021-05-01,Simona Serena
2,aAR0M0000001unaWAA,670006,0010M00001SmqRAQAZ,[Account],Focus,$0,NaN,NaN,56.0,4. Activation,NaN,864,0.79,Lightning Enabled,-5.02,40.000000,44.000000,57.14,2021-06-01,NaN
3,aAR0M0000001v6YWAQ,671182,0010M00001QmstNQAR,[Account],Top,$10k-50k,NaN,NaN,28.0,4. Activation,47.0,1406,0.09,Lightning Enabled,1.66,83.144919,86.908113,81.08,2021-06-01,NaN
4,aAR0M0000001uiqWAA,669712,0010M00001SmqRUQAZ,[Account],Focus,$0,NaN,NaN,63.0,1. Awareness,NaN,576,0.79,No Lightning Usage,-4.88,33.333333,38.666667,33.33,2021-06-01,NaN

In [ ]:
# add counter
testSprog['Sprog Count'] = 1
testSprog.head(5)

In [ ]:
SprogPivot1 = pd.pivot_table(testSprog, values='Sprog Count', index=['RecordType.Name'], aggfunc= np.sum)
SprogPivot1

In [ ]:
SprogPivot2 = pd.pivot_table(testSprog, values='Sprog Count', index=['Delivery_Method__c'], aggfunc= np.sum)
SprogPivot2

In [ ]:
AccUUID.head(5)

In [ ]:
del AccUUID['_']
AccUUID.head(5)

In [ ]:
AccUUID.describe()

In [ ]:
import uuid

In [ ]:
AccUUID['uuid'] = [uuid.uuid4() for x in range(len(AccUUID))] 
AccUUID.head(5)

In [ ]:
testAcc = pd.read_csv('/Users/jdear/test-account.csv')
testAcc.columns

In [ ]:
df = pd.merge(AccUUID, testAcc, on='Id', how='left')
df.head()

In [ ]:
AccUUID.to_csv('UUIDmapping.csv')